word_list = [
    "abacaxi", "abelha", "abobora", "abril", "abismo", "acucar", "agulha", "alegria", "algodao", "almofada",
    "amarelo", "amizade", "amor", "aniversario", "anel", "animais", "antena", "apartamento", "apito", "arco",
    "areia", "argila", "arvore", "asfalto", "atleta", "atmosfera", "atomo", "aventura", "avenida", "aviador",
    "balcao", "balde", "bambu", "banana", "barco", "barulho", "bateria", "beija", "beira", "bicicleta",
    "biscoito", "bloco", "bola", "bolha", "bolo", "boneca", "borboleta", "bosque", "branco", "brilho",
    "cabana", "cabelo", "cachorro", "cafe", "caju", "calendario", "calor", "camera", "campo", "caneta",
    "canto", "capitulo", "caracol", "caravana", "carta", "casaco", "caverna", "cebola", "cimento", "cidade",
    "claridade", "clima", "coelho", "cofre", "colecao", "comando", "comida", "computador", "concha", "conquista",
    "corda", "coracao", "corredor", "coruja", "cortina", "costura", "cozinhar", "cravo", "creme", "criar",
    "cristal", "cruzeiro", "danca", "dedo", "defesa", "dentista", "descanso", "desenho", "deserto", "detalhe",
    "diamante", "diferente", "dificil", "dinamico", "disco", "dominio", "dormir", "duvida", "eco", "edificio",
    "efeito", "elegante", "eleicao", "eletricidade", "embarcacao", "emocao", "energia", "enigma", "entrada", "enxame",
    "epoca", "escada", "esfera", "esmalte", "esporte", "espuma", "estacao", "estrela", "estudante", "exercito",
    "experiencia", "exploracao", "fabrica", "fada", "faixa", "familia", "fantasia", "farol", "fartura", "feliz",
    "ferias", "festa", "figura", "filme", "final", "fita", "flor", "foco", "fonte", "formiga",
    "fosforo", "fruta", "futuro", "galinha", "galo", "gasolina", "geleia", "geleira", "gigante", "girafa",
    "giro", "giz", "goiaba", "governo", "grama", "grande", "gravata", "guarda", "guerreiro", "gremio",
    "habilidade", "helicoptero", "historia", "homem", "hora", "horta", "hotel", "humano", "humor", "ilha",
    "idade", "ideia", "ilha", "imagem", "imovel", "infantil", "infeliz", "inverno", "irmao", "irmandade",
    "jabuticaba", "jardim", "jarra", "jato", "jogo", "joia", "jornal", "jovem", "julho", "juridico",
    "ketchup", "kilograma", "kilometro", "kiwi", "koala", "kart", "kaleidoscopio", "karate", "karaoke", "kabuki",
    "lago", "lampada", "lapis", "laranja", "leite", "leopardo", "limao", "livro", "lobo", "lua",
    "macaco", "madeira", "mamifero", "manada", "manga", "manta", "mar", "margarida", "marrom", "mato",
    "natureza", "navio", "neblina", "neve", "negocio", "ninho", "nobreza", "noite", "nome", "norma",
    "objeto", "oceano", "oculos", "oficina", "olhar", "onda", "operacao", "opcao", "ordem", "orgulho",
    "ovo", "ovelha", "ovoide", "oxigenio", "paisagem", "pao", "papel", "paraiso", "pato", "peixe",
    "piano", "pijama", "pilha", "pintura", "pipoca", "planta", "pocao", "porta", "praia", "presente",
    "quadrado", "quadro", "quente", "querer", "quilo", "quimica", "raio", "rato", "rede", "reino",
    "relampago", "relogio", "remedio", "rio", "rosa", "rubro", "sabao", "sala", "samba", "sapo",
    "saturno", "segredo", "sol", "sombra", "som", "sorriso", "tartaruga", "teatro", "tela", "tempo",
    "terra", "tigre", "tiro", "tocha", "tomate", "torre", "touro", "trabalho", "trem", "treno",
    "universo", "urso", "uva", "uvaia", "velho", "ventania", "vento", "verde", "verme", "vidro",
    "viagem", "vida", "violino", "vulcao", "xarope", "xadrez", "xale", "xicara", "zangao", "zebra",
    "zoologico", "gremio"
]
