jogadores = [
    {"nome": "Pelé", "time": "Santos", "gols": 1281},
    {"nome": "Zico", "time": "Flamengo", "gols": 526},
    {"nome": "Romário", "time": "Flamengo", "gols": 1000},
    {"nome": "Ronaldo Fenômeno", "time": "Real Madrid", "gols": 352},
    {"nome": "Ronaldinho Gaúcho", "time": "Barcelona", "gols": 316},
    {"nome": "Neymar", "time": "Paris Saint-Germain", "gols": 405},
    {"nome": "Cafu", "time": "AS Roma", "gols": 29},
    {"nome": "Roberto Carlos", "time": "Real Madrid", "gols": 127},
    {"nome": "Kaká", "time": "AC Milan", "gols": 237},
    {"nome": "Rivaldo", "time": "Barcelona", "gols": 240},
    {"nome": "Dunga", "time": "Flamengo", "gols": 26},
    {"nome": "Sócrates", "time": "Corinthians", "gols": 210},
    {"nome": "Falcão", "time": "Roma", "gols": 98},
    {"nome": "Tostão", "time": "Cruzeiro", "gols": 221},
    {"nome": "Bebeto", "time": "Flamengo", "gols": 253},
    {"nome": "Gilberto Silva", "time": "Arsenal", "gols": 27},
    {"nome": "Cleverton", "time": "Grêmio", "gols": 8},
    {"nome": "Alex", "time": "Corinthians", "gols": 148},
    {"nome": "Rogério Ceni", "time": "São Paulo", "gols": 131},
    {"nome": "Ricardinho", "time": "Corinthians", "gols": 57},
    {"nome": "Ricardo Goulart", "time": "Cruzeiro", "gols": 106},
    {"nome": "Diego", "time": "Flamengo", "gols": 157},
    {"nome": "William", "time": "Chelsea", "gols": 160},
    {"nome": "Lúcio", "time": "Bayern de Munique", "gols": 20},
    {"nome": "Tião", "time": "Flamengo", "gols": 74},
    {"nome": "Júnior", "time": "Flamengo", "gols": 59},
    {"nome": "Basilio", "time": "Flamengo", "gols": 59},
    {"nome": "Zé Roberto", "time": "Bayern de Munique", "gols": 172},
    {"nome": "Nílton Santos", "time": "Botafogo", "gols": 22},
    {"nome": "Jairzinho", "time": "Botafogo", "gols": 163},
    {"nome": "Djalma Santos", "time": "Palmeiras", "gols": 11},
    {"nome": "Vavá", "time": "Atlético de Madrid", "gols": 221},
    {"nome": "Careca", "time": "Napoli", "gols": 176},
    {"nome": "Sócrates", "time": "Corinthians", "gols": 104},
    {"nome": "Raí", "time": "São Paulo", "gols": 147},
    {"nome": "Borges", "time": "São Paulo", "gols": 134},
    {"nome": "Marcelo", "time": "Real Madrid", "gols": 38},
    {"nome": "Alexandre Pato", "time": "AC Milan", "gols": 138},
    {"nome": "Diego Souza", "time": "Grêmio", "gols": 190}
]